// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

import java.awt.Color;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   public static int leftDrivePort = 0;
   public static int rightDrivePoint = 1;
   public static double deadzone = 0.1;

   public static final int LightBank1 = 1;
   public static final int LightBank2 = 2;
   public static float defaultRed = 1f;
   public static float defaultGreen = 1f;
   public static float defaultBlue = 1f;
   public static double LightSpeed = 0.01;
   public static float MaxBrightness = 1f;
   public static Color allianceRedColor = new Color(1f,0f, 0f);
   public static Color allianceBlueColor = new Color(0f,0f, 1f);
}

