// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.motorcontrol.Spark;
import edu.wpi.first.wpilibj2.command.SubsystemBase;



// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Prototyping extends SubsystemBase {
    private Spark spark_4 = new Spark(4);    
    private Spark spark_5 = new Spark(5);
    private Spark spark_6 = new Spark(6);
    private Spark spark_7 = new Spark(7);
    private Spark spark_8 = new Spark(8);
    private Spark spark_9 = new Spark(9);
    private Spark[] sparkList;
    public Prototyping() {
        sparkList = new Spark[] {spark_4, spark_5, spark_6, spark_7, spark_8, spark_9};
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void runSpark(int port, double speed){
        if(4 <= port && port <= 9){
            sparkList[port-4].set(speed);
        }
    }
}

